services:
  app:
    image: ghcr.io/adiachenko/frankenstack:8.5
    restart: unless-stopped
    environment:
      PHP_ENV: production
      FRANKENPHP_MODE: worker
      FRANKENPHP_WORKERS: 2
      FRANKENPHP_MAX_REQUESTS: 500
    ports:
      - 8000:80
    volumes:
      - ./:/opt/project
